# -*- coding: utf-8 -*-
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
a = [1,1,0]
ans = 0
while a[2] <= 4000000:
  a[2] = a[1] + a[0]
  a[0] = a[1]
  a[1] = a[2]
  if not(a[2] & 1):
    ans += a[2]

print ans
